

world_address = "0x03b95b1b1d3d504d0b841294cec694e6d088192fc22c0ac2e083ff2df2e844b7"

[server]
http_cors_origins = ["*"]


[indexing]
pending = true
polling_interval = 1000
namespaces=["dopewars", "dope"]

# max_concurrent_tasks = 2
contracts = [
    "ERC20:0x020dfc24de987d7d11f70a7306ae39b6ac71b178eaf19bf12e831b3522c14ebf", # paper
    #
    "ERC721:0x001ee0fe152c71643aa7c6325c9e2d8278c2ed1da681733ec90f64be98ac6645", # dope_loot
    "ERC721:0x01fb30a6baa133d7bc0ad072ace31b86447392877d190ce2bf8f3616733d8524", # dope_hustlers
    "ERC1155:0x0165a15fec164ea2e183f4d37770fd82a5cb467f07b06dc8d51192bbb5c87155", # dope_gear
]

[erc]
max_metadata_tasks=100


[sql]
historical = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]
