
rpc = "https://api.cartridge.gg/x/dopewars/katana"

world_address = "0x03b95b1b1d3d504d0b841294cec694e6d088192fc22c0ac2e083ff2df2e844b7"

[server]
http_cors_origins = ["*"]


[indexing]
pending = true
polling_interval = 250
namespaces=["dopewars", "dope"]

# max_concurrent_tasks = 2
contracts = [
    "ERC20:0x020dfc24de987d7d11f70a7306ae39b6ac71b178eaf19bf12e831b3522c14ebf", # paper
    #
    "ERC721:0x001ee0fe152c71643aa7c6325c9e2d8278c2ed1da681733ec90f64be98ac6645", # dope_loot
    "ERC721:0x01c14abe1d25b8c10b89958a6bc6f2441ece48312a35d29916d5d1bea592f1f0", # dope_hustlers
    "ERC1155:0x06c6b927a731087377aa5d7caf57aa1dec7ed5d0c16b231ba0a6e216dec48f92", # dope_gear
]

[erc]
max_metadata_tasks=100

[sql]
historical = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]
