

world_address = "0x07c199e52347fad3214ccdc9cb65e8b467d0773936a21a4d4080e462e4f271b5"

[server]
http_cors_origins = ["*"]


[indexing]
pending = true
polling_interval = 1000

# max_concurrent_tasks = 2
contracts = [
    "ERC20:0x0381ebd1ff06f9379be332ffc2b3dc145bb0816f7f12cb8649490f2a88438b7f", # paper
    #
    "ERC721:0x02ef6f3a7706826e1e136502b040ec4a27080b9299e237a1bc68f8043b25a121", # dope_loot
    "ERC721:0x058a861b41208e6fe5e7e3fbf3b831557c1d9eb469e28c58a7f206ea400521a4", # dope_hustlers
    "ERC1155:0x01fc27c28756995a6641a0b3e8cdc463c51642815f1bae74e583930f4318283d", # dope_gear
]

[erc]
max_metadata_tasks=100


[sql]
historical = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]
