

world_address = "0x0481a7d7b499c8ba774ab492787e8f2678ff63d3ba33ab513b29a79e31f6c0b8"

[server]
http_cors_origins = ["*"]


[indexing]
pending = true
polling_interval = 1000
namespaces=["dopewars_v0", "dope"]

# max_concurrent_tasks = 2
contracts = [
    # "ERC20:0x07911f16dc122877dee96a1ec2cc1f8a6853096253568118047b5e1e0edba17c", # paper
    #
    "ERC721:0x07347c03891acbb8667a444fa82a4e66b0e8cea4c6c7949c13137aa151f1035d", # dope_loot
    "ERC721:0x057fa07a7ba53b055afee628d1306edaeda056ce4f680bac8bad25d1e5375650", # dope_hustlers
    "ERC1155:0x0030d87d480893027e621bd608b21e3b9efdadd23a705458083e94c028479bb0", # dope_gear
]

[erc]
max_metadata_tasks=100


[sql]
historical = [
    "dopewars_v0-GameCreated",
    "dopewars_v0-Traveled",
    "dopewars_v0-GameOver",
    "dopewars_v0-TradeDrug",
    "dopewars_v0-HighVolatility",
    "dopewars_v0-UpgradeItem",
    "dopewars_v0-TravelEncounter",
    "dopewars_v0-TravelEncounterResult",
    "dopewars_v0-NewSeason",
    "dopewars_v0-NewHighScore",
    "dopewars_v0-Claimed",
    # bushido 
    "dopewars_v0-TrophyCreation",
    "dopewars_v0-TrophyProgression",
]

