rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_7"

world_address = "0x04f3dccb47477c087ad9c76b8067b8aadded57f8df7f2d7543e6066bcb25332c"

[indexing]
allowed_origins = ["*"]
pending = true
transactions = false
polling_interval = 1000
contracts = []

[events]
raw = true    
historical = [
    "dopewars_v0-GameCreated",
    "dopewars_v0-Traveled",
    "dopewars_v0-GameOver",
    "dopewars_v0-TradeDrug",
    "dopewars_v0-HighVolatility",
    "dopewars_v0-UpgradeItem",
    "dopewars_v0-TravelEncounter",
    "dopewars_v0-TravelEncounterResult",
    "dopewars_v0-NewSeason",
    "dopewars_v0-NewHighScore",
    "dopewars_v0-Claimed",
    # bushido 
    "dopewars_v0-TrophyCreation",
    "dopewars_v0-TrophyProgression",
]
