
rpc = "https://api.cartridge.gg/x/dopewars/katana"

world_address = "0x05d133456420b786bca33391f7b472b4f7af4fdd9d507ef50d85cc5cc19f8e56"

[server]
http_cors_origins = ["*"]


[indexing]
pending = true
polling_interval = 1000

# max_concurrent_tasks = 2
contracts = [
    "ERC20:0x06f2b2838cd8eb0902e52c73a66cca0cc5c2de641aa969eb9c93e4306906eb78", # paper
    #
    "ERC721:0x016094ef477812ed35e10847fd335517312030e2ed4f8cbd5a746980085f2823", # dope_loot
    "ERC721:0x027ba14794b7567025f1d7206090b545f48e3ce5a442eda5e95ae16906d5fc0e", # dope_hustlers
    "ERC1155:0x000727c84f146c9c0e80ad0743a183425a3b34b49955863cb3c889c99e7e7081", # dope_gear
]

[erc]
max_metadata_tasks=100

[sql]
historical = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]
